version: "3.8"

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gigglemap
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
