version: "3.8"

services:
  app:
    build: .
    container_name: gigglemap-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://giggle:giggle123@postgres:5432/gigglemap
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - gigglemap-net

  postgres:
    image: postgres:14
    container_name: gigglemap-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: giggle
      POSTGRES_PASSWORD: giggle123
      POSTGRES_DB: gigglemap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gigglemap-net

  redis:
    image: redis:7-alpine
    container_name: gigglemap-redis
    ports:
      - "6379:6379"
    networks:
      - gigglemap-net

volumes:
  postgres_data:

networks:
  gigglemap-net:
    driver: bridge
